# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- the-first-pipeline

pool:
  vmImage: ubuntu-latest

steps:
- hosts: localhost
  tasks:

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts