## colete as informações de IP, OS Family, Distribuição e quantidade de memória do VSTS agent
- hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        var: ansible_facts["all_ipv4_addresses"]
    - debug:
        var: ansible_facts["os_family"]
    - debug:
        var: ansible_facts["distribution"]
    - debug:
        var: ansible_facts["memory_mb"]
    
    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
        path: /tmp/testfile
        line: Teste !
        create: yes